# Generated by Django 4.2.5 on 2023-10-20 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_rating", models.SmallIntegerField(default=0)),
                (
                    "author_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_title",
                    models.CharField(db_index=True, max_length=56, unique=True),
                ),
                ("post_text", models.TextField()),
                ("post_date", models.DateField(auto_now_add=True)),
                ("post_rating", models.SmallIntegerField(default=0)),
                (
                    "post_type",
                    models.CharField(
                        choices=[("AR", "Статья"), ("NW", "Новость")],
                        default="AR",
                        max_length=2,
                    ),
                ),
                (
                    "post_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to="moykotel.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="moykotel.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_avatar",
                    models.ImageField(default="default.jpg", upload_to="img/users/"),
                ),
                ("user_phone", models.CharField(default="+7000000000", max_length=10)),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("AD", "Администратор"),
                            ("MG", "Контентв-менеджер"),
                            ("SV", "Сервисный центр"),
                            ("CL", "Заказчик"),
                        ],
                        default="CL",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_through",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moykotel.category",
                    ),
                ),
                (
                    "post_through",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="moykotel.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="post_category",
            field=models.ManyToManyField(
                related_name="posts",
                through="moykotel.PostCategory",
                to="moykotel.category",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField()),
                ("comment_date", models.DateTimeField(auto_now_add=True)),
                ("comment_rating", models.SmallIntegerField(default=0)),
                (
                    "comment_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="moykotel.post",
                    ),
                ),
                (
                    "comment_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_authors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
