# Generated by Django 4.2.4 on 2023-09-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moykotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_title",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
