# Generated by Django 4.2.4 on 2023-09-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moykotel", "0002_alter_post_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_category",
            field=models.ManyToManyField(
                related_name="posts",
                through="moykotel.PostCategory",
                to="moykotel.category",
            ),
        ),
    ]
