# Generated by Django 4.2.5 on 2023-10-25 14:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moykotel", "0002_category_subscribers"),
    ]

    operations = [
        migrations.RenameModel(old_name="Subscriptions", new_name="Subscriber",),
    ]
