# Generated by Django 4.2.5 on 2023-10-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moykotel", "0003_rename_subscriptions_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="latest_newsletter",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
