# Generated by Django 4.2.4 on 2023-09-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moykotel", "0004_alter_post_post_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_category",
            field=models.ManyToManyField(
                related_name="posts",
                through="moykotel.PostCategory",
                to="moykotel.category",
            ),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="category_through",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="moykotel.category"
            ),
        ),
    ]
