# Generated by Django 4.2.4 on 2023-09-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moykotel", "0005_alter_post_post_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_title",
            field=models.CharField(db_index=True, max_length=56, unique=True),
        ),
    ]
