# Generated by Django 4.2.5 on 2023-10-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moykotel", "0006_alter_category_subscribers"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscriber", name="latest_newsletter",),
        migrations.AlterField(
            model_name="subscriber",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="moykotel.category"
            ),
        ),
    ]
