# Generated by Django 4.2.5 on 2023-10-27 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moykotel", "0007_remove_subscriber_latest_newsletter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscrition_category",
                to="moykotel.category",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
