# Generated by Django 4.2.5 on 2023-10-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moykotel", "0008_alter_subscriber_category_alter_subscriber_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_category",
                to="moykotel.category",
            ),
        ),
    ]
